### ISSUE TITLE
Hi! A great work! When will the code be released?

### ISSUE THREAD

**Issue by DLwbm123** [csm9493/GAN2GAN#1]

**Comment by csm9493** [comment]
Thanks for your interest.
Our goal is to upload the official code of our paper before starting ICLR 2021.

We are trying to upload as quickly as possible, so we would appreciate your patience.

Sincerely,
Sungmin Cha

**Comment by ztt0821** [comment]
Hi, May I ask when will release the official code? Thank you very much.

**Comment by hust-lidelong** [comment]
Hi, May I ask when will release the official code? Thank you very much.

**Comment by csm9493** [comment]
The official code is released now.
Sorry for the late upload.
