### ISSUE TITLE
How to generate BSD dataset for training?

### ISSUE THREAD

**Issue by hust-lidelong** [csm9493/GAN2GAN#5]
Nice work!
I want to train GAN2GAN for the BSD dataset? How to generate a training dataset? Thanks!

**Comment by csm9493** [comment]
Sorry for the late reply.

Because I uploaded all pretrained weights of GAN2GAN on BSD experiments, I didn't arrange the code for generating a training dataset for BSD.
Actually, the process for generating the training dataset is almost similar with the process for test dataset (generate training dataset with BSD400 by following the description in the paper). Therefore, if you want to generate the training dataset, please refer to the uploaded ipython code ('data/Generate_BSD_test_dataset.ipynb').

Thanks. :)

**Comment by hust-lidelong** [comment]
> Sorry for the late reply.
> 
> Because I uploaded all pretrained weights of GAN2GAN on BSD experiments, I didn't arrange the code for generating a training dataset for BSD. Actually, the process for generating the training dataset is almost similar with the process for test dataset (generate training dataset with BSD400 by following the description in the paper). Therefore, if you want to generate the training dataset, please refer to the uploaded ipython code ('data/Generate_BSD_test_dataset.ipynb').
> 
> Thanks. :)

Thanks for your reply!
I have a question:
https://github.com/csm9493/GAN2GAN/blob/main/main_test.py#L33
https://github.com/csm9493/GAN2GAN/blob/main/main_test.py#L42
https://github.com/csm9493/GAN2GAN/blob/main/main_test.py#L51
https://github.com/csm9493/GAN2GAN/blob/main/main_test.py#L60
https://github.com/csm9493/GAN2GAN/blob/main/main_test.py#L69
They all load the same weight 'BSD_DnCNN_B_N2C.w'
Why? Thanks!

If I want to train DnCNN-B denoisers and GAN2GAN denoiser for my own dataset, how to do? Thanks for your  reply!

**Comment by csm9493** [comment]
1. Q: 'They all load the same weight 'BSD_DnCNN_N2C.w' why?
A) DnCNN-B is trained on a range of sigma (\sigma = [0, 55]) of Gaussian noise so it is a single model (not a multiple model). Therefore, same weights are loaded for the experiment on DnCNN-B

2. If I want to train DnCNN-B denoisers and GAN2GAN denoiser for my own dataset, how to do?
A) If you want to train a denoiser via GAN2GAN, please check the below comment (it is copied from QnA in README.md)

You can easily customize ipynb files in './data/' to generate custom training dataset. Note that a lambda (the hyperparameter for controlling the level of homoneousity) for smooth_area_detector() should be selected carefully. Our empirical recommendation is to set a lambda that can extract at least 10,000 noise patches.

For training a DnCNN-B denoiser, you should have a set of clean images. And then, you have to make a set of noisy images by corrupting it with Gaussian noise (\sigma = [0, 55]) for generating a pair of the clean and noisy images. Please check the details from the DnCNN paper (https://arxiv.org/abs/1608.03981)
